#!/usr/bin/env php
<?php

declare(strict_types=1);

use App\Execute\ExecuteArgs;

define('SCOOB_START', microtime(true));

require './vendor/autoload.php';

echo "      ----              ------   ------   -----   -----  |------  \n";
echo "    --------           |        |        |     | |     | |      | \n";
echo "   |  -  -  |           ------  |        |     | |     | |------  \n";
echo "       --   (^^^= - - -       | |        |     | |     | |      | \n";
echo "       ||  //           ------   ------   -----   -----  |------  \n";
echo "       || //                                                      \n";
echo "       ||                                                         \n";
echo "   -------------------------------------------------------------- \n";
echo "   SCOOB ESTÁ TRABALHANDO PARA TE AJUDAR - AGUARDE COM PACIÊNCIA! \n";
echo "\n";

ExecuteArgs::run($argv);

