#!/usr/bin/env php
<?php

declare(strict_types=1);

use App\Execute\ExecuteArgs;

define('SCOOB_START', microtime(true));

exec("chmod -R 755 vendor/shieldforce/easy-docker/");

require './vendor/autoload.php';

ExecuteArgs::run($argv);

