#!/usr/bin/env php
<?php

declare(strict_types=1);

use App\Execute\ExecuteArgs;

define('SCOOB_START', microtime(true));

require './vendor/autoload.php';

echo "      ---       ";
echo "    -------     ";
echo "   | -- -- |    ";
echo "      ---       ";

ExecuteArgs::run($argv);

