### Args ------------------------
ARG PHP_VERSION
ARG EXPOSE_PORT
### Args ------------------------

### Version ---------------------
FROM php:${PHP_VERSION}-fpm

### IMplements -------
### IMplements -------
### IMplements -------
RUN apt-get update


#COPY ./scripts/start.sh /start.sh
#RUN chmod 755 /start.sh

### Port Expose ----------------
EXPOSE ${EXPOSE_PORT}

#CMD ["/bin/bash", "/start.sh"]
