### Args ------------------------
ARG PHP_VERSION
ARG PHP_PORT
### Args ------------------------

### Version ---------------------
FROM php:${PHP_VERSION}-fpm


### Port Expose ----------------
EXPOSE ${PHP_PORT}
